POST http://localhost:5000/passwordless/api/register
Content-Type: application/json

{
  "userId": "eb4dee07-2d05-404e-80ed-0f65d0c4e30e",
  "displayName": null,
  "username": "TestUser",
  "attestation": "none",
  "authenticatorType": "any",
  "discoverable": true,
  "userVerification": "preferred",
  "aliases": [],
  "aliasHashing": true,
  "expiresAt": "2023-09-09T20:07:02.365573Z"
}

<> 2023-09-09T220829.200.json

###
POST http://localhost:5000/passwordless/api/login
Content-Type: application/json

{
  "token": "verify_k8QgiPlgfMVr34FyFipBrkj6jBwKT9QifsFx-DSa1L3Yp_PE1NwAE9f_ppPH0GT80Y_ZJDBlZGQ2NWJjLTliOGQtNGIxYS1iMjA4LTIxYzZjOGYxYWQ5NK5wYXNza2V5X3NpZ25pbsDAwMDAwMDZJGViNGRlZTA3LTJkMDUtNDA0ZS04MGVkLTBmNjVkMGM0ZTMwZdf_ppOx8GT80RepbG9jYWxob3N0tWh0dHA6Ly9sb2NhbGhvc3Q6ODA4MMOzQ2hyb21lLCBNYWMgT1MgWCAxMKJQTMDEIGbZgozerTjDOV_ysX2AKQByPuZ-guCkcvWDHjKnzY4_zhU3BlI"
}

<> 2023-09-09T221057.200.json

###
POST http://localhost:5000/passwordless/api/alias
Content-Type: application/json

{
  "userId": "eb4dee07-2d05-404e-80ed-0f65d0c4e30e",
  "aliases": [
    "TestUserAlias1",
    "TestUserAlias2"
  ],
  "hashing": true
}

###
GET http://localhost:5000/passwordless/api/alias/eb4dee07-2d05-404e-80ed-0f65d0c4e30e

<> 2023-09-09T221245.200.json

###
PUT http://localhost:5000/passwordless/api/apps/feature
Content-Type: application/json

{
  "auditLoggingRetentionPeriod":  50
}

###
GET http://localhost:5000/passwordless/api/credentials/eb4dee07-2d05-404e-80ed-0f65d0c4e30e

<> 2023-09-09T221423.200.json

###
DELETE http://localhost:5000/passwordless/api/credentials
Content-Type: application/json

{
  "credentialId": "ZtmCjN6tOMM5X_KxfYApAHI-5n6C4KRy9YMeMqfNjj8"
}

###
GET http://localhost:5000/passwordless/api/users

<> 2023-09-09T221516.200.json

###
DELETE http://localhost:5000/passwordless/api/users
Content-Type: application/json

{
  "userId": "eb4dee07-2d05-404e-80ed-0f65d0c4e30e"
}
